# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90813829bed48e608f2f33f014266b03db9710cd31269c66a00ef44b565317055e3042d255b9f7a3b134e6a0b99c0cb5bbe26bdbc11fd3f74ce9ca06d4bde6f2

test:
  secret_key_base: 61681e836f9e147928c0ba0f0836d2e3a5af8f51146507a5b861f0619d742141347f60a7bd76a2acf6d71e2aeaf338d2e7d1ef41799960570b4fd66397afa9fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
